//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filter3ValidateInputAllowHTML
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        //[AllowHtml]
        public string Description { get; set; }
    }
}
// Allow HTML is an attribute which can be used to allow HTML input into a single field